### ISSUE TITLE
Idea: use standard GTFS data format

### ISSUE THREAD

**Issue by tuukka** [w32blaster/helsinki-timetables#1]
The idea I'm suggesting is to change from the old Finnish Kalkati XML format to the current standard GTFS format. The GTFS format is a zipped archive of various spreadsheets in CSV format: stops.txt, routes.txt, trips.txt etc. This is the format that HSL's new beta journey planner imports, and it's the format that is most widely used around the world: https://transitfeeds.com/

This way, the same app could work all around the world depending on whose GTFS data you load.

GTFS specification: https://developers.google.com/transit/gtfs/reference/

**Comment by w32blaster** [comment]
Good idea, it would be awesome. I will take a look at that specs

**Comment by w32blaster** [comment]
The information to migrate to the GTFS is here: http://developer.reittiopas.fi/pages/en/other-apis.php
