### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by airon90** [w32blaster/helsinki-timetables#3]
Is it possible to add this app on [F-Droid](https://f-droid.org)? [I already filled a request](https://gitlab.com/fdroid/rfp/issues/715) to package it in the official repo but I forgot to advice you.

**Comment by w32blaster** [comment]
yes, sure, I will try. Cheers

**Comment by w32blaster** [comment]
I left the comment in the repository, let me know if I can do something else for you

**Comment by airon90** [comment]
Thank you very much! :)
